CREATE TABLE [dbo].[TDS_t_Emp_Details] (
    [Sevaarth_Id]        NVARCHAR (15)  NOT NULL,
    [DDO_Code]           NVARCHAR (11)  NULL,
    [EMP_PANNo]          NVARCHAR (10)  NULL,
    [PAN_Status]         NVARCHAR (1)   NULL,
    [UID_No]             NVARCHAR (12)  NULL,
    [EID_No]             NVARCHAR (50)  NULL,
    [Name_AsPerSevaarth] NVARCHAR (50)  NULL,
    [DBO_AsPerSevaarth]  DATE           NULL,
    [Name_AsPerIT]       NVARCHAR (50)  NULL,
    [DBO_AsPerIT]        DATE           NULL,
    [Designation_Id]     INT            NULL,
    [DOJ]                DATE           NULL,
    [DOR]                DATE           NULL,
    [Contact_No]         NVARCHAR (13)  NULL,
    [Email_Id]           NVARCHAR (50)  NULL,
    [Gender_Id]          INT            NULL,
    [Address]            NVARCHAR (255) NULL,
    [IsManual]           NVARCHAR (1)   NULL,
    [IsSeniorCitizen]    NVARCHAR (1)   NULL,
    [IsDCPS]             NVARCHAR (1)   NULL,
    [InsertedOn]         DATETIME       NULL,
    [InsertedBy]         INT            NULL,
    [UpdatedOn]          DATETIME       NULL,
    [updatedBy]          INT            NULL,
    [Status]             NVARCHAR (1)   NULL,
    CONSTRAINT [PK_Emp_Details] PRIMARY KEY CLUSTERED ([Sevaarth_Id] ASC)
);

