CREATE TABLE [dbo].[TDS_t_EmpYearlyGRecov_Details] (
    [Recov_Id]                         INT           IDENTITY (1, 1) NOT NULL,
    [Yealy_Id]                         INT           NULL,
    [Proffession_Tax]                  NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Proffession_Tax] DEFAULT ((0)) NULL,
    [Proffession_Tax_Arrears]          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Proffession_Tax_Arrears] DEFAULT ((0)) NULL,
    [Income_Tax]                       NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Income_Tax] DEFAULT ((0)) NULL,
    [DCPS_Employee_Contribution]       NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_DCPS_Employee_Contribution] DEFAULT ((0)) NULL,
    [DCPS_Pay_Arrear]                  NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_DCPS_Pay_Arrear] DEFAULT ((0)) NULL,
    [DCPS_Pay_Arrears_Recovery]        NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_DCPS_Pay_Arrears_Recovery] DEFAULT ((0)) NULL,
    [DCPS_Regular_Recovery]            NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_DCPS_Regular_Recovery] DEFAULT ((0)) NULL,
    [DCPS_DA_Arrears_Recovery]         NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_DCPS_DA_Arrears_Recovery] DEFAULT ((0)) NULL,
    [DCPS_Delayed_Recovery]            NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_DCPS_Delayed_Recovery] DEFAULT ((0)) NULL,
    [DedAdj_Employer_Contribution]     NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_DedAdj_Employer_Contribution] DEFAULT ((0)) NULL,
    [GIS]                              NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GIS] DEFAULT ((0)) NULL,
    [Central_GIS]                      NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Central_GIS] DEFAULT ((0)) NULL,
    [GIS_IAS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GIS_IAS] DEFAULT ((0)) NULL,
    [GIS_IFS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GIS_IFS] DEFAULT ((0)) NULL,
    [GIS_IPS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GIS_IPS] DEFAULT ((0)) NULL,
    [GIS_ZP]                           NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GIS_ZP] DEFAULT ((0)) NULL,
    [GIS_Arrear]                       NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GIS_Arrear] DEFAULT ((0)) NULL,
    [GIS_Arrears_Recovery]             NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GIS_Arrears_Recovery] DEFAULT ((0)) NULL,
    [Contributory_PF]                  NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Contributory_PF] DEFAULT ((0)) NULL,
    [GPF_IAS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_IAS] DEFAULT ((0)) NULL,
    [GPF_IAS_OtherState]               NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_IAS_OtherState] DEFAULT ((0)) NULL,
    [GPF_IFS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_IFS] DEFAULT ((0)) NULL,
    [GPF_IPS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_IPS] DEFAULT ((0)) NULL,
    [GPF_GRP_ABC]                      NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_GRP_ABC] DEFAULT ((0)) NULL,
    [GPF_ADV_GRP_ABC]                  NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_ADV_GRP_ABC] DEFAULT ((0)) NULL,
    [GPF_GRP_D]                        NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_GRP_D] DEFAULT ((0)) NULL,
    [GPF_ADV_GRP_D]                    NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_ADV_GRP_D] DEFAULT ((0)) NULL,
    [GPF_ABC_Arrears]                  NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_ABC_Arrears] DEFAULT ((0)) NULL,
    [GPF_D_Arrears]                    NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_D_Arrears] DEFAULT ((0)) NULL,
    [GPF_IAS_Arrears]                  NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_IAS_Arrears] DEFAULT ((0)) NULL,
    [GPF_IFS_Arrears]                  NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_GPF_IFS_Arrears] DEFAULT ((0)) NULL,
    [Group_Account_Policy]             NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Group_Account_Policy] DEFAULT ((0)) NULL,
    [House_Rent_Recovery]              NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_House_Rent_Recovery] DEFAULT ((0)) NULL,
    [HRR_Arrear]                       NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HRR_Arrear] DEFAULT ((0)) NULL,
    [MSLI]                             NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_MSLI] DEFAULT ((0)) NULL,
    [PLI]                              NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_PLI] DEFAULT ((0)) NULL,
    [Service_Charge_and_Garage_Charge] NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Service_Charge_and_Garage_Charge] DEFAULT ((0)) NULL,
    [Service_Charge_Arr]               NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Service_Charge_Arr] DEFAULT ((0)) NULL,
    [Co_Housing_Society]               NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Co_Housing_Society] DEFAULT ((0)) NULL,
    [Co_Housing_Society_Interest]      NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Co_Housing_Society_Interest] DEFAULT ((0)) NULL,
    [Computer_Advance]                 NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Computer_Advance] DEFAULT ((0)) NULL,
    [Comp_Adv_Int]                     NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Comp_Adv_Int] DEFAULT ((0)) NULL,
    [Comp_AIS_Int]                     NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Comp_AIS_Int] DEFAULT ((0)) NULL,
    [Recovery_of_Overpayment]          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Recovery_of_Overpayment] DEFAULT ((0)) NULL,
    [FA]                               NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_FA] DEFAULT ((0)) NULL,
    [HBA_Principal]                    NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_Principal] DEFAULT ((0)) NULL,
    [HBA_Interest]                     NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_Interest] DEFAULT ((0)) NULL,
    [HBA_AIS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_AIS] DEFAULT ((0)) NULL,
    [HBA_AIS_Int]                      NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_AIS_Int] DEFAULT ((0)) NULL,
    [HBA_For_Land]                     NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_For_Land] DEFAULT ((0)) NULL,
    [HBA_For_Land_Int]                 NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_For_Land_Int] DEFAULT ((0)) NULL,
    [HBA_House]                        NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_House] DEFAULT ((0)) NULL,
    [HBA_House_Int]                    NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HBA_House_Int] DEFAULT ((0)) NULL,
    [HIS]                              NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_HIS] DEFAULT ((0)) NULL,
    [MCA]                              NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_MCA] DEFAULT ((0)) NULL,
    [MCA_Interest]                     NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_MCA_Interest] DEFAULT ((0)) NULL,
    [MCA_AIS]                          NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_MCA_AIS] DEFAULT ((0)) NULL,
    [MCA_AIs_Int]                      NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_MCA_AIs_Int] DEFAULT ((0)) NULL,
    [Other_Adv]                        NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Other_Adv] DEFAULT ((0)) NULL,
    [Other_Adv_Int]                    NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Other_Adv_Int] DEFAULT ((0)) NULL,
    [Other_Vehical_Advance]            NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Other_Vehical_Advance] DEFAULT ((0)) NULL,
    [Other_Vehical_Advance_Interest]   NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Other_Vehical_Advance_Interest] DEFAULT ((0)) NULL,
    [Pay_Advance]                      NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Pay_Advance] DEFAULT ((0)) NULL,
    [TA_Advance]                       NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_TA_Advance] DEFAULT ((0)) NULL,
    [Other_GRecov]                     NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Other_GRecov] DEFAULT ((0)) NULL,
    [Total_GRecoveries]                NVARCHAR (10) CONSTRAINT [DF_EmpGRecov_Details_Total_GRecoveries] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_EmpGRecov_Details] PRIMARY KEY CLUSTERED ([Recov_Id] ASC),
    CONSTRAINT [FK_EmpGRecov_Details_EmpYearly_Details] FOREIGN KEY ([Yealy_Id]) REFERENCES [dbo].[TDS_t_EmpYearly_Details] ([Yealy_Id]) ON DELETE CASCADE ON UPDATE CASCADE
);

