CREATE TABLE [dbo].[TDS_t_EmdbMasterData] (
    [Emdb_Id]                  INT            IDENTITY (1, 1) NOT NULL,
    [Sevaarth_Id]              NVARCHAR (15)  NULL,
    [Emp_FullName]             NVARCHAR (MAX) NULL,
    [EMP_PANNo]                NVARCHAR (10)  NULL,
    [Emp_Name_AsPerIT]         NVARCHAR (MAX) NULL,
    [PAN_Status]               NVARCHAR (1)   NULL,
    [TANNo]                    NVARCHAR (15)  NULL,
    [DDO_Code]                 NVARCHAR (15)  NULL,
    [Scheme]                   NVARCHAR (50)  NULL,
    [PostType]                 NVARCHAR (50)  NULL,
    [Designation]              NVARCHAR (50)  NULL,
    [Gender]                   NVARCHAR (1)   NULL,
    [Religion]                 NVARCHAR (15)  NULL,
    [SocialGroup]              NVARCHAR (MAX) NULL,
    [UID_No]                   NVARCHAR (12)  NULL,
    [Education]                NVARCHAR (50)  NULL,
    [DOB]                      DATE           NULL,
    [DOJ]                      DATE           NULL,
    [DOR]                      DATE           NULL,
    [TypeOfDisability]         NVARCHAR (50)  NULL,
    [IsResidingInGovtQuarters] NVARCHAR (1)   NULL,
    [ApplicablePayCommission]  NVARCHAR (MAX) NULL,
    [EID_No]                   NVARCHAR (50)  NULL,
    [ContactNo]                NVARCHAR (10)  NULL,
    [WhatsAppNo]               NVARCHAR (10)  NULL,
    [Email_Id]                 NVARCHAR (50)  NULL,
    [Address]                  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_EmdbMasterData] PRIMARY KEY CLUSTERED ([Emdb_Id] ASC)
);

