CREATE TABLE [dbo].[TDS_t_EmpYearlyGNonRecov_Details] (
    [NonRec_Id]            INT           IDENTITY (1, 1) NOT NULL,
    [Yealy_Id]             INT           NULL,
    [Bank_Loan_1]          NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Bank_Loan_1] DEFAULT ((0)) NULL,
    [Bank_Loan_2]          NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Bank_Loan_2] DEFAULT ((0)) NULL,
    [Co_Op_Bank_1]         NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Co_Op_Bank_1] DEFAULT ((0)) NULL,
    [Co_Op_Bank_2]         NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Co_Op_Bank_2] DEFAULT ((0)) NULL,
    [Co_Op_Cr_Soc_1]       NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Co_Op_Cr_Soc_1] DEFAULT ((0)) NULL,
    [Co_Op_Cr_Soc_2]       NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Co_Op_Cr_Soc_2] DEFAULT ((0)) NULL,
    [Co_Op_Hsg_Soc]        NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Co_Op_Hsg_Soc] DEFAULT ((0)) NULL,
    [LIC_1]                NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_LIC_1] DEFAULT ((0)) NULL,
    [LIC_2]                NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_LIC_2] DEFAULT ((0)) NULL,
    [LIC_3]                NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_LIC_3] DEFAULT ((0)) NULL,
    [Other_Recovery_1]     NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Other_Recovery_1] DEFAULT ((0)) NULL,
    [Other_Recovery_2]     NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Other_Recovery_2] DEFAULT ((0)) NULL,
    [RD_1]                 NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_RD_1] DEFAULT ((0)) NULL,
    [RD_2]                 NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_RD_2] DEFAULT ((0)) NULL,
    [Con_Store]            NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Con_Store] DEFAULT ((0)) NULL,
    [Matralaya_Bank]       NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Matralaya_Bank] DEFAULT ((0)) NULL,
    [Mess_Recovery]        NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Mess_Recovery] DEFAULT ((0)) NULL,
    [Miscellaneous]        NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Miscellaneous] DEFAULT ((0)) NULL,
    [Elec_Charge]          NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Elec_Charge] DEFAULT ((0)) NULL,
    [Maintenance_Charge]   NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Maintenance_Charge] DEFAULT ((0)) NULL,
    [Tel_Charge]           NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Tel_Charge] DEFAULT ((0)) NULL,
    [Water_Charge]         NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Water_Charge] DEFAULT ((0)) NULL,
    [Club_Fund]            NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Club_Fund] DEFAULT ((0)) NULL,
    [Mess_Dev_Fund]        NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Mess_Dev_Fund] DEFAULT ((0)) NULL,
    [Welfare_Fund]         NVARCHAR (10) NULL,
    [Other_GNonRecov]      NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Other_GNonRecov] DEFAULT ((0)) NULL,
    [Total_GNonRecoveries] NVARCHAR (10) CONSTRAINT [DF_EmpGNonRecov_Details_Total_GNonRecoveries] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_EmpGNonRecov_Details] PRIMARY KEY CLUSTERED ([NonRec_Id] ASC),
    CONSTRAINT [FK_EmpGNonRecov_Details_EmpYearly_Details] FOREIGN KEY ([Yealy_Id]) REFERENCES [dbo].[TDS_t_EmpYearly_Details] ([Yealy_Id])
);

