USE [TDSLive];
GO

Create OR Alter View [dbo].[EmployeeData_v0]
--***********************************************************
--***
--*** Created On 02 Oct 2025 By A.R.Gawande
--***
--***********************************************************
AS

	--Get Employee Salary Information
	SELECT	eyd.Yealy_Id
			,eyd.Sevaarth_Id
			,eyd.DDO_Code
			,eyd.Voucher_Id
			,eyd.Fin_Year
			,eyd.Bill_Month
			,eyd.Bill_Year
			,eyd.PayBill_Type
			,eyd.Vourcher_Date
			,eyd.Voucher_No
			,eyd.Net_Pay
			,eyd.[Status]
			,gd.Gross_Id
			,gd.PayIn_PB_GP
			,gd.Basic_Pay
			,gd.Basic_Arrear
			,gd.Official_Pay
			,gd.Personal_Pay
			,gd.CLA_Pay
			,gd.Special_Pay
			,gd.Writer_Pay
			,gd.Leave_Salary
			,gd.DA
			,gd.DA_7PC
			,gd.Additional_DA
			,gd.Central_DA
			,gd.DA_Arrear
			,gd.DA_On_TA
			,gd.Dearness_Pay
			,gd.Additional_Pay
			,gd.HRA
			,gd.Additional_HRA
			,gd.HRA_Arrear
			,gd.HRA_Pay
			,gd.TA
			,gd.TA_Arrears
			,gd.TA_Pay
			,gd.Central_TA
			,gd.Leave_TA
			,gd.DCPS_Employer_Contribution
			,gd.ATC_Incentive_50
			,gd.ATC_Incentive_30
			,gd.Force_Incentive_100
			,gd.Force_Incentive_25
			,gd.Incentive_For_BDDS
			,gd.Arm_Allowance
			,gd.Armourer_Allowance
			,gd.BMI_Allowance
			,gd.CHPL_CPL_Allowance
			,gd.CID_Allowance
			,gd.Cash_Allowance
			,gd.Children_Educ_Allowance
			,gd.Convenyance_Allowance
			,gd.ESIS_Allowance
			,gd.Emergency_Allowance
			,gd.Extra_Lecture_Allowance
			,gd.Family_Planning_Allowance
			,gd.Fitness_Allowance
			,gd.Franking_Allowance
			,gd.Hilly_Allowance
			,gd.Kit_Maintenance_Allowance
			,gd.Mechanical_Allowance
			,gd.Med_St_Allowance
			,gd.Medical_Allowance_MA
			,gd.Medical_Education_Allowance
			,gd.Mess_Allowance
			,gd.Naxal_Area_Allowance
			,gd.Non_Practicing_Allowance
			,gd.Other_Allowances
			,gd.Other_Miscellaneous_Allowance
			,gd.Outfit_Allowance
			,gd.Peon_Allowance
			,gd.Permanent_Travelling_Allowance
			,gd.Post_Graduation_Allowance
			,gd.Project_Allowance
			,gd.Qualification_Allowance
			,gd.Refreshment_Allowance
			,gd.Special_Duty_Allowance
			,gd.Sumptuary_Allowance
			,gd.Technical_Allowance
			,gd.Tribal_Allowance
			,gd.Uniform_Allowance
			,gd.Washing_Allowance
			,gd.Flying_Allowance_For_Pilot
			,gd.Inspection_Allowance_For_Pilot
			,gd.Instructional_Allowance_For_Pilot
			,gd.Flying_Pay_For_Pilot_Cons
			,gd.Militery_Serv_Pay_Pilot
			,gd.RT_Allowance_For_Pilot
			,gd.Special_Pay_For_Pilot
			,gd.Gallantry_Awards
			,gd.IR_For_Judges
			,gd.License_Free
			,gd.UCTC
			,gd.Partially_Fully_Tax_Free
			,gd.Other
			,gd.Total_Gross
			,rd.Recov_Id
			,rd.Proffession_Tax
			,rd.Proffession_Tax_Arrears
			,rd.Income_Tax
			,rd.DCPS_Employee_Contribution
			,rd.DCPS_Pay_Arrear
			,rd.DCPS_Pay_Arrears_Recovery
			,rd.DCPS_Regular_Recovery
			,rd.DCPS_DA_Arrears_Recovery
			,rd.DCPS_Delayed_Recovery
			,rd.DedAdj_Employer_Contribution
			,rd.GIS
			,rd.Central_GIS
			,rd.GIS_IAS
			,rd.GIS_IFS
			,rd.GIS_IPS
			,rd.GIS_ZP
			,rd.GIS_Arrear
			,rd.GIS_Arrears_Recovery
			,rd.Contributory_PF
			,rd.GPF_IAS
			,rd.GPF_IAS_OtherState
			,rd.GPF_IFS
			,rd.GPF_IPS
			,rd.GPF_GRP_ABC
			,rd.GPF_ADV_GRP_ABC
			,rd.GPF_GRP_D
			,rd.GPF_ADV_GRP_D
			,rd.GPF_ABC_Arrears
			,rd.GPF_D_Arrears
			,rd.GPF_IAS_Arrears
			,rd.GPF_IFS_Arrears
			,rd.Group_Account_Policy
			,rd.House_Rent_Recovery
			,rd.HRR_Arrear
			,rd.MSLI
			,rd.PLI
			,rd.Service_Charge_and_Garage_Charge
			,rd.Service_Charge_Arr
			,rd.Co_Housing_Society
			,rd.Co_Housing_Society_Interest
			,rd.Computer_Advance
			,rd.Comp_Adv_Int
			,rd.Comp_AIS_Int
			,rd.Recovery_of_Overpayment
			,rd.FA
			,rd.HBA_Principal
			,rd.HBA_Interest
			,rd.HBA_AIS
			,rd.HBA_AIS_Int
			,rd.HBA_For_Land
			,rd.HBA_For_Land_Int
			,rd.HBA_House
			,rd.HBA_House_Int
			,rd.HIS
			,rd.MCA
			,rd.MCA_Interest
			,rd.MCA_AIS
			,rd.MCA_AIs_Int
			,rd.Other_Adv
			,rd.Other_Adv_Int
			,rd.Other_Vehical_Advance
			,rd.Other_Vehical_Advance_Interest
			,rd.Pay_Advance
			,rd.TA_Advance
			,rd.Other_GRecov
			,rd.Total_GRecoveries
			,nrd.NonRec_Id
			,nrd.Bank_Loan_1
			,nrd.Bank_Loan_2
			,nrd.Co_Op_Bank_1
			,nrd.Co_Op_Bank_2
			,nrd.Co_Op_Cr_Soc_1
			,nrd.Co_Op_Cr_Soc_2
			,nrd.Co_Op_Hsg_Soc
			,nrd.LIC_1
			,nrd.LIC_2
			,nrd.LIC_3
			,nrd.Other_Recovery_1
			,nrd.Other_Recovery_2
			,nrd.RD_1
			,nrd.RD_2
			,nrd.Con_Store
			,nrd.Matralaya_Bank
			,nrd.Mess_Recovery
			,nrd.Miscellaneous
			,nrd.Elec_Charge
			,nrd.Maintenance_Charge
			,nrd.Tel_Charge
			,nrd.Water_Charge
			,nrd.Club_Fund
			,nrd.Mess_Dev_Fund
			,nrd.Welfare_Fund
			,nrd.Other_GNonRecov
			,nrd.Total_GNonRecoveries
	FROM TDS_t_EmpYearly_Details eyd with(nolock)
	LEFT JOIN TDS_t_EmpYearlyGross_Details gd with(nolock) ON eyd.Yealy_Id=gd.Yealy_Id
	LEFT JOIN TDS_t_EmpYearlyGRecov_Details rd with(nolock) ON eyd.Yealy_Id=rd.Yealy_Id
	LEFT JOIN TDS_t_EmpYearlyGNonRecov_Details nrd with(nolock) ON eyd.Yealy_Id=nrd.Yealy_Id

GO